# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

main:
  docker:
    registry:
      url: "gcr.io/keller-covered/kc-frontend-eo"
      username: ""
      password: ""
  dependencies:
    postgres: true
  labels:
    app: kc-frontend-eo
  selectorLabels:
    app: kc-frontend-eo
  hpa:
    maxReplicas: 10
    minReplicas: 3
    cpuAverageUtilization: 70
    memoryAverageUtilization: 70
  deployment:
    containerPort: 3000
    replicaCount: 3
    resources:
      requests:
        cpu: 5m # Idle 4m
        memory: 130mi # Idle 100mi
      limits:
        cpu: 7m
        memory: 300mi
    podSecurityContext: {}
    securityContext: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    image:
      repository: "gcr.io/keller-covered/kc-frontend-eo"
      pullPolicy: Always
    imagePullSecrets:
      - name: kc-frontend-eo-docker-registry-secrets
    envSecrets: []
      # - name: "STAGE"
      #   value: "development"
  service:
    type: ClusterIP
    port: 3000
  serviceAccount:
    create: true
  virtualService:
    create: false
    uriPrefix: "/kc-frontend-eo"
    uriRewrite: "/"
    hosts: 
    - "bancus-dev.applaudostudios.com"
    serviceHost: kc-frontend-eo
    gateways:
    - global-gateway