sudo: required
dist: xenial
language: node_js

cache:
  directories:
    - '~/.npm'
    - '~/.cache'
    - '~/.yarn'
    - '~/.yarn-cache'

services:
  - docker

node_js:
  - '12.16.2'

branches:
  only:
    - master
    - staging
    - develop
    - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - DOCKER_IMAGE_NAME='kc-frontend-eo'
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      if: branch IN (develop, staging) AND type = pull_request
      name: specs
      before_install: npm i -g yarn
      install: yarn --frozen-lockfile
      script:
        - if [[ $TRAVIS_BRANCH  == "develop" ]]; then yarn format; fi
    - stage: deploy
      if: type = push
      name: deploy
      before_install:
        - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
        - chmod +x ./kubectl
        - sudo mv ./kubectl /usr/local/bin/kubectl
        - mv ./.kube/ /home/travis
        - if [ ! -d $HOME/google-cloud-sdk/bin ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash > /dev/null; fi
        - source $HOME/google-cloud-sdk/path.bash.inc
        - gcloud components update kubectl
        - '/home/travis/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ./key.json'
        - gcloud config set project starlit-myth-275818
        - gcloud -q auth configure-docker
      script:
        - |
          if [[ $TRAVIS_BRANCH  == "develop" && $TRAVIS_PULL_REQUEST == "false" ]]; then
            docker build --build-arg build_option=build-development -t $DOCKER_IMAGE_NAME-dev . && \
            docker tag $DOCKER_IMAGE_NAME-dev gcr.io/starlit-myth-275818/$DOCKER_IMAGE_NAME-dev:$COMMIT && \
            docker push gcr.io/starlit-myth-275818/$DOCKER_IMAGE_NAME-dev:$COMMIT && \
            kubectl --kubeconfig=/home/travis/.kube/config config use-context gke_starlit-myth-275818_us-central1-c_cluster-1 && \
            kubectl --kubeconfig=/home/travis/.kube/config apply -f deployment-config-nginx.yml && \
            kubectl --kubeconfig=/home/travis/.kube/config apply -f deployment.yml && \
            kubectl --kubeconfig=/home/travis/.kube/config set image deployments/$DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME=gcr.io/starlit-myth-275818/$DOCKER_IMAGE_NAME-dev:$COMMIT;
          fi
