os: linux
dist: xenial

language: node_js
node_js:
  - '12.16.2'
  
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
    - "$HOME/ci-tools/bin/"
#     - "$HOME/docker_images/"

# before_script:
# - docker load -i $HOME/docker_images/images.tar || true

# before_cache:
# - docker save -o $HOME/docker_images/images.tar $(docker images -a -q)

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - DOCKER_IMAGE_NAME='kc-frontend-eo'
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - CHART_NAME=kc-frontend-eo
    - CHART_NAMESPACE=kc-frontend
stages:
  # - test
  - deploy

jobs:
  include:
    - stage: test
      install: yarn install
      script:
        - yarn test

    - stage: Deploy
      if: (branch IN (k8s-deployment-dev) OR tag IS present) AND type NOT IN (pull_request, cron)
      name: "Deployment"
      install: ./ci-cd/scripts/install.sh
      script: ./ci-cd/scripts/deploy.sh
