sudo: required
dist: xenial
language: node_js

cache:
  directories:
    - '~/.npm'
    - '~/.cache'
    - '~/.yarn'

services:
  - docker

node_js:
  - 'lts/*'

branches:
  only:
    - master
    - staging
    - develop
    - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - DOCKER_IMAGE_NAME='kc-frontend-eo'

stages:
  - test
  - deploy

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  include:
    - stage: test
      if: branch IN (develop, staging) AND type = pull_request
      name: specs
      install: yarn --non-interactive --frozen-lockfile
      script:
        - if [[ $TRAVIS_BRANCH  == "develop" ]]; then yarn format; fi
