apiVersion: apps/v1
kind: Deployment
metadata:
  name: kc-frontend-eo
  labels:
    app: kc-frontend-eo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kc-frontend-eo
  template:
    metadata:
      labels:
        app: kc-frontend-eo
    spec:
      containers:
        - name: kc-frontend-eo
          image: gcr.io/starlit-myth-275818/kc-frontend-eo:latest
          volumeMounts:
            - name: kc-frontend-eo
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
            - name: robots-config
              mountPath: /etc/nginx/conf.d/robots.txt
              subPath: robots.txt
            - name: htpasswd
              mountPath: /etc/nginx/conf.d/.htpasswd
              subPath: htpasswd
          resources:
            requests:
              memory: '100Mi'
              cpu: '50m'
            limits:
              memory: '150Mi'
              cpu: '75m'
          livenessProbe:
              httpGet:
                path: /healthz
                port: 80
              initialDelaySeconds: 30
              timeoutSeconds: 1
          ports:
            - name: web
              containerPort: 80
      volumes:
        - name: kc-frontend
          configMap:
            name: kc-frontend-eo-nginx
        - name: robots-config
          configMap:
            name: robots-config
        - name: htpasswd
          configMap:
            name: htpasswd
---
apiVersion: v1
kind: Service
metadata:
  name: kc-frontend-eo
spec:
  selector:
    app: kc-frontend-eo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
