version: '3.4'
services: 
  web:
    build:
      context: .
      target: base
      dockerfile: ci-cd/docker/Dockerfile
      args:
        NPM_TOKEN: ${NPM_TOKEN}
        NODE_ENV: ${NODE_ENV}
        APP_ENV: ${APP_ENV}
    volumes:
      - "./pages:/workspace/pages"
      - "./static:/workspace/static"
      - "./ci-cd:/workspace/ci-cd"
      - "./src:/workspace/src"
    ports:
      - "3000:3000"
    env_file: .env
