export const SET_PAGE_LOCATION = 'SET_PAGE_LOCATION';
export const FIRM_CONFIRMATION_STORE = 'FIRM_CONFIRMATION_STORE';
export const CHANGE_STATUS_PROGRESS_BAR = 'CHANGE_STATUS_PROGRESS_BAR';
export const AGENT_INFORMATION_STORE = 'AGENT_INFORMATION_STORE';
export const SET_INFORMATION_PAGE = 'SET_INFORMATION_PAGE';
