apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helpers.fullname" . }}-env-secret
type: Opaque
stringData:
  {{- range .Values.main.deployment.envSecrets }}
    {{ .name | quote }}: {{ .value | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "helpers.fullname" . }}-docker-registry-secrets
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "helpers.imagePullSecret" . }} 