{{- if .Values.main.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helpers.serviceAccountName" . }}
  labels:
{{ include "helpers.labels" . | nindent 4 }}
{{- end -}}
